# Generated by Django 5.0.4 on 2024-04-28 06:33

from django.db import migrations

def load_initial_data(apps, schema_editor):
    Category = apps.get_model('budget', 'Category')
    object = apps.get_model('budget', 'BudgetObject')
    Category.objects.create(name='Extra')
    Category.objects.create(name='Emergency Fund')
    # object.objects.create (name='YAHOO')

class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
