# Generated by Django 5.0.4 on 2024-04-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_auto_20240428_0633"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("publication_date", models.DateField()),
            ],
        ),
    ]
