# Generated by Django 5.0.4 on 2024-04-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.CharField(max_length=100)),
                ("phase", models.CharField(max_length=100)),
                ("deliverable", models.CharField(max_length=100)),
                ("task", models.CharField(max_length=100)),
                ("hoursWorked", models.IntegerField(max_length=100)),
            ],
        ),
    ]
